config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    default_url_options :host => "localhost:3000"
    root "static_pages#home"
    get "/careers/new", to: "careers#new"
    get "/careers/edit", to: "careers#edit"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/password_resets/new", to: "password_resets#new"
    get "password_resets/edit", to: "password_resets#edit"
    resources :users, :careers
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :jobs
    resources :curriculum_vitaes
    resources :user_curriculum_vitaes
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :career
  has_many :user_jobs, dependent: :destroy
  has_many :users, through: :user_jobs
  validates :title, presence: true, length: {maximum: Settings.max_length_title}
  validates :salary, :amount, presence: true, numericality: true
  validates :rank, :skill, presence: true,
    length: {maximum: Settings.max_length_rank}
  validates :language, presence: true,
    length: {maximum: Settings.max_length_lang}
  validates :experience, :description, presence: true
  validates :publish_date, :expiration_date, presence: true, date: true

  scope :selected,
    ->{select :id, :title, :salary, :experience, :expiration_date}
  scope :ordered, ->{order created_at: :desc}
  scope :company_name, (lambda do |name|
    includes(:users).where(User.arel_table[:name].matches("%#{name}%")
      .or(User.arel_table[:address].matches("%#{name}%"))).references(:users)
  end)
  scope :job_info, (lambda do |info|
    where(Job.arel_table[:title].matches("%#{info}%")
      .or(Job.arel_table[:salary].matches("%#{info}%"))
      .or(Job.arel_table[:rank].matches("%#{info}%")))
  end)
  scope :career_name, (lambda do |name|
    joins(:career).where(Career.arel_table[:name].matches("%#{name}%"))
  end)

  class << self
    def career_options
      @career_options = Career.all.map{|p| [p.name, p.id]}
    end

    def cv_options user
      @cv_options = user.curriculum_vitaes.map{|p| [p.target, p.id]}
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :logged_in_user, :employeer_user,
    only: %i(new create edit update destroy)
  before_action :find_job, only: %i(show edit update destroy)

  def index
    @jobs = Job.ordered.page(params[:page]).per Settings.per_sheet
    %w(career_name company_name job_info).each do |p|
      search_job p, @jobs
    end
  end

  def new
    @career_options = Job.career_options
    @job = current_user.jobs.new
  end

  def create
    @career_options = Job.career_options
    @job = current_user.jobs.build job_params

    if @job.save
      @job.user_jobs.create! user_id: current_user.id, job_id: @job.id
      flash[:success] = t ".success"
      redirect_to @job
    else
      flash[:danger] = t ".error"
      render :new
    end
  end

  def show
    @user = @job.users.find_by role: "employeer"

    return unless logged_in?
    @cv_options = Job.cv_options current_user
    @user_cv = @user.user_curriculum_vitaes.build

    return if @user
    flash[:danger] = t ".user_employeer"
    redirect_to root_path
  end

  def edit
    @career_options = Job.career_options
  end

  def update
    if @job.update job_params
      flash[:success] = t ".success"
      redirect_to @job
    else
      flash[:danger] = t ".error"
      render :edit
    end
  end

  def destroy
    if @job.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".error"
    end
    redirect_to root_url
  end

  private

  def find_job
    @job = Job.find_by id: params[:id]

    return if @job
    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  def employeer_user
    return if current_user.employeer?
    flash[:danger] = t ".not_permit"
    redirect_to root_path
  end

  def search_job option, job
    return unless params[option].present?
    @jobs = job.send(option, params[option]).ordered.page(params[:page])
               .per Settings.per_sheet
  end

  def job_params
    params.require(:job).permit :career_id, :title, :salary, :rank, :skill,
      :language, :amount, :experience, :description,
      :publish_date, :expiration_date
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def jobs_new job
    @user = job.users.find_by role: "employeer"
  end
end

app/views/jobs/_apply.html.erb
<%= form_with model: @user_cv, local: true do |f| %>
  <div><%= hidden_field_tag :user_id, @user.id %></div>
  <%= f.label :curriculum_vitae_id, t(".select") %>
  <%= f.select :curriculum_vitae_id, options_for_select(@cv_options),
    include_blank: t(".choose_cv"), class: "form-control" %>
  <%= f.submit t(".apply"), class: "btn btn-primary button" %>
<% end %>

app/views/jobs/_job.html.erb
<div class="col-sm-6 e-left">
  <div class="e-desc">
    <h6 class="text-uppercase"><%= link_to job.title, job %></h6>
    <hr>
    <ul class="desc-list">
      <li>
        <span><%= t ".company" %></span>
        <%= jobs_new(job).name %>
      </li>
      <li>
        <span><%= t ".salary" %></span>
        <%= job.salary %>
      </li>
      <li>
        <span><%= t ".experience" %></span>
        <%= job.experience %>
      </li>
      <li>
        <span><%= t ".expiration_date" %></span>
        <%= job.expiration_date %>
      </li>
    </ul>
    <%= link_to t(".detail"), job, class: "btn wthree-bnr-btn text-capitalize" %>
  </div>
</div>

app/views/jobs/edit.html.erb
<% provide :title, t(".update_job") %>
<h1><%= t ".update_job" %></h1>

<div class="row form_cn">
  <div class="col-md-8 col-md-offset-4">
    <%= form_with model: @job, local: true do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :title, t(".title") %>
      <%= f.text_area :title, class: "form-control", placeholder: "abc" %>

      <%= f.label :career_id, t(".career_id") %>
      <%= f.select :career_id, options_for_select(@career_options),
        include_blank: t(".choose_career"), class: "form-control" %>

      <%= f.label :salary, t(".salary") %>
      <%= f.text_field :salary, class: "form-control" %>

      <%= f.label :rank, t(".rank") %>
      <%= f.text_field :rank, class: "form-control" %>

      <%= f.label :skill, t(".skill") %>
      <%= f.text_field :skill, class: "form-control" %>

      <%= f.label :language, t(".language") %>
      <%= f.text_field :language, class: "form-control" %>

      <%= f.label :amount, t(".amount") %>
      <%= f.text_field :amount, class: "form-control" %>

      <%= f.label :experience, t(".experience") %>
      <%= f.text_area :experience, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :publish_date, t(".publish_date") %>
      <%= f.date_field :publish_date, class: "form-control" %>

      <%= f.label :expiration_date, t(".expiration_date") %>
      <%= f.date_field :expiration_date, class: "form-control" %>

      <%= f.submit t(".update_btn") , class: "btn btn-lg btn-success" %>
    <% end %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="title-sec-w3layouts_pvt text-center pt-4">
      <span class="title-wthree"><%= t ".find_result" %></span>
  </div>
  <div class="row">
    <% if @jobs.present? %>
      <%= render @jobs %>
    <% else %>
      <p><%= t ".not_found" %></p>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= paginate @jobs, theme: "twitter-bootstrap-3" %>
  </div>
</div>

app/views/jobs/new.html.erb
<% provide :title,  t(".job")  %>
<h1><%= t ".job" %></h1>

<div class="row form_cn">
  <div class="col-md-8 col-md-offset-4">
    <%= form_with model: @job, local: true do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :title, t(".title") %>
      <%= f.text_area :title, class: "form-control" %>

      <%= f.label :career_id, t(".career_id") %>
      <%= f.select :career_id, options_for_select(@career_options),
        include_blank: t(".choose_career"), class: "form-control" %>

      <%= f.label :salary, t(".salary") %>
      <%= f.text_field :salary, class: "form-control" %>

      <%= f.label :rank, t(".rank") %>
      <%= f.text_field :rank, class: "form-control" %>

      <%= f.label :skill, t(".skill") %>
      <%= f.text_field :skill, class: "form-control" %>

      <%= f.label :language, t(".language") %>
      <%= f.text_field :language, class: "form-control" %>

      <%= f.label :amount, t(".amount") %>
      <%= f.text_field :amount, class: "form-control" %>

      <%= f.label :experience, t(".experience") %>
      <%= f.text_area :experience, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :publish_date, t(".publish_date") %>
      <%= f.date_field :publish_date, class: "form-control" %>

      <%= f.label :expiration_date, t(".expiration_date") %>
      <%= f.date_field :expiration_date, class: "form-control" %>

      <%= f.submit t(".create_job") , class: "btn btn-primary button" %>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<% provide :title, @job.title %>
<div >
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= image_tag "evolable-asia-logo.png" %>
      </div>
      <div class="col-md-9 job_info">
        <h1><%= @job.title%></h1>

        <h5><%= t ".company" %></h5><hr>
        <p><%= @user.name %></p><br>

        <h5><%= t ".career" %></h5><hr>
        <p><%= @job.career.name %></p><br>

        <h5><%= t ".salary" %></h5><hr>
        <p><%= @job.salary %></p><br>

        <h5><%= t ".amount" %></h5><hr>
        <p><%= @job.amount %></p><br>

        <h5><%= t ".rank" %></h5><hr>
        <p><%= @job.rank %></p><br>

        <h5><%= t ".skill" %></h5><hr>
        <p><%= @job.skill %></p><br>

        <h5><%= t ".language" %></h5><hr>
        <p><%= @job.language %></p><br>

        <h5><%= t ".experience" %></h5><hr>
        <p><%= @job.experience %></p><br>

        <h5><%= t ".description" %></h5><hr>
        <p><%= @job.description %></p><br>

        <h5><%= t ".phone" %></h5><hr>
        <p><%= @user.phone %></p><br>

        <h5><%= t ".address" %></h5><hr>
        <p><%= @user.address %></p><br>

        <h5><%= t ".publish_date" %></h5><hr>
        <p><%= @job.publish_date %></p><br>

        <h5><%= t ".expiration_date" %></h5><hr>
        <p><%= @job.expiration_date %></p><br>
        <div class="button_cn">
        <% if @user.current_user? current_user %>
          <%= link_to t(".update"), edit_job_path,
            class: "btn btn-lg btn-success" %>
          <%= link_to t(".delete"), job_path, method: :delete,
            data: {confirm: t(".sure")}, class: "btn btn-lg btn-danger" %>
        <% end %>
        <% if !logged_in? || current_user.candidate? %>
          <%= link_to t(".apply"), new_user_curriculum_vitae_path, class:
            "btn wthree-bnr-btn text-capitalize", data: {toggle: "modal",
              target: "#applyCV"} %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="applyCV" tabindex="-1" role="dialog"
  aria-labelledby="login_or_apply" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header bg-theme1">
        <h5 class="modal-title" id="login_or_apply">
          <% if !logged_in? %>
            <%= t ".r_login" %>
          <% else %>
            <%= t ".select_cv" %>
          <% end %>
        </h5>
        <button type="button" class="close" data-dismiss="modal"
          aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if !logged_in? %>
        <div class="button_cn">
          <%= link_to t("signup"), signup_path, class: "btn btn-lg btn-warning" %>
          <%= link_to t("login"), login_path, class: "btn btn-lg btn-warning" %>
        </div>
        <% else %>
          <%= render "apply" %>
        <% end %>
      </div>
    </div>
  </div>
</div>