config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    default_url_options :host => "localhost:3000"
    root "static_pages#home"
    get "/careers/new", to: "careers#new"
    get "/careers/edit", to: "careers#edit"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/password_resets/new", to: "password_resets#new"
    get "password_resets/edit", to: "password_resets#edit"
    resources :users, :careers
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :jobs
    resources :curriculum_vitaes
    resources :user_curriculum_vitaes
  end
end

app/models/career.rb
class Career < ApplicationRecord
  has_many :jobs
  validates :name, presence: true, uniqueness: true,
    length: {maximum: Settings.max_length_name}
  validates :description, presence: true
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  before_action :find_career, only: %i(show edit update destroy)

  def index
    @careers = Career.page(params[:page]).per Settings.per_sheet
  end

  def show
    return if @career
    flash[:danger] = t ".not_found_careers"
    redirect_to root_path
  end

  def new
    @career = Career.new
  end

  def create
    @career = Career.new career_params

    if @career.save
      flash[:success] = t ".create_career_success"
      redirect_to @career
    else
      flash[:danger] = t ".error"
      render :new
    end
  end

  def edit; end

  def update
    if @career.update career_params
      flash[:success] = t ".update_success"
      redirect_to @career
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  def destroy
    if @career.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_fail"
    end
    redirect_to career_path
  end

  private

  def career_params
    params.require(:career).permit :name, :description
  end

  def find_career
    @career = Career.find_by id: params[:id]

    return if @career
    flash[:danger] = t ".not_found_careers"
    redirect_to root_path
  end
end

app/views/careers/edit.html.erb
<% provide :title, t(".edit_career") %>
<h1><%= t ".edit_career" %></h1>
<div class="row signup">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @career, url: career_path, local: true do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".career_name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.submit t(".update") , class: "btn btn-primary submit" %>
    <% end %>
  </div>
</div>

app/views/careers/index.html.erb
<% provide :title, t(".career_list") %>
<h1><%= t ".career_list" %></h1>
<ul class="users">
  <% @careers.each do |career| %>
  <li class="fa fa-th">
  <%= link_to career.name, career %>
  | <%= link_to t(".delete"), career, method: :delete,
    data: { confirm: t(".confirm") } %>
  | <%= link_to t(".edit"), edit_career_path(career.id) %>
  </li>
  <br/>
  <% end %>
</ul>
<%= paginate @careers, theme: "twitter-bootstrap-3" %>

app/views/careers/new.html.erb
<% provide :title,  t(".add_career")  %>
<h1><%= t ".add_career" %></h1>

<div class="row signup">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @career, url: careers_path, local: true do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".career_name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.submit t(".create_career") , class: "btn btn-primary submit" %>
    <% end %>
  </div>
</div>

app/views/careers/show.html.erb
<% provide :title, @career.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="career_info">
      <h1 class="fa fa-star">
        <%= t ".description" %>
        <%= @career.description%>
      </h1>
    </section>
  </aside>
</div>