config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    default_url_options :host => "localhost:3000"
    root "static_pages#home"
    get "/careers/new", to: "careers#new"
    get "/careers/edit", to: "careers#edit"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/password_resets/new", to: "password_resets#new"
    get "password_resets/edit", to: "password_resets#edit"
    resources :users, :careers
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :jobs
    resources :curriculum_vitaes
    resources :user_curriculum_vitaes
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="py-sm-5 py-4 bg-theme footer">
  <div class="container">
    <div class="footer-top-w3ls">
      <h2><%= link_to t("base_title"), "#", class: "navbar-brand" %></h2>
    </div>
    <div class="row pt-5">
      <div class="col-lg-6 footer_grid1">
        <h5><%= t "address" %></h5>
        <div class="d-flex align-items-center">
          <span class="fa fa-building mr-4"></span>
          <p>90 Street, landmark, City State 34189.</p>
        </div>
        <div class="d-flex mt-3 align-items-center">
          <span class="fa fa-building mr-4"></span>
          <p>16 Street, landmark, City State 74789.</p>
        </div>
      </div>
      <div class="col-lg-6 mt-lg-0 mt-5">
        <h5>Quick links</h5>
        <ul class="list-unstyled quick-links">
          <li>
            <span class="fa fa-play"></span>
            <%= link_to t("static_pages.home.title"), "#" %>
          </li>
          <li>
            <span class="fa fa-play"></span>
            <%= link_to t("about"), "#" %>
          </li>
          <li>
            <span class="fa fa-play"></span>
            <%= link_to t("contact"), "#" %>
          </li>
          <li>
            <span class="fa fa-play"></span>
            <%= link_to t("help"), "#" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light p-0 navbar-static-top">
      <h1 class="title"><%= link_to t("base_title"), root_path, class: "navbar-brand" %></h1>
      <button class="navbar-toggler ml-lg-auto ml-sm-5 bg-light" type="button"
        data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="ml-lg-5 navbar-nav mr-lg-auto">
          <li class="nav-item mr-lg-4 mt-lg-0 mt-sm-4 mt-3">
            <%= link_to t("createCV"), new_curriculum_vitae_path %>
          </li>
          <li class="nav-item  mr-lg-4 mt-lg-0 mt-sm-4 mt-3">
            <%= link_to t("createJob"), new_job_path %>
          </li>
        </ul>
        <% if logged_in? %>
        <li class="dropdown nav-item mr-lg-4 mt-lg-0 mt-sm-4 mt-3">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
            <%= t ".manager"%>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t(".users"), users_path %></li>
            <li><%= link_to t(".add_career"), new_career_path %></li>
            <li><%= link_to t(".careers"), careers_path %></li>
          </ul>
        </li>
        <li class="dropdown nav-item mr-lg-4 mt-lg-0 mt-sm-4 mt-3">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
            <%= t ".account"%>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t(".profile"), current_user %></li>
            <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to t(".log_out"), logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <%= link_to t("signup"), signup_path, class: "btn w3ls-btn text-uppercase font-weight-bold d-block" %>
        <%= link_to t("login"), login_path, class: "btn w3ls-btn btn-2 ml-lg-1 text-uppercase font-weight-bold d-block" %>
        <% end %>
        <div class="laguage">
          <%= link_to locale: "en" do %>
            <%= image_tag "en.png" %>
          <% end %>
          <%= link_to locale: "vi" do %>
            <%= image_tag "vi.png" %>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</header>
<div class="d-flex banner-w3pvt-bg1 common-bg header">
  <div class="d-flex mx-auto align-items-center justify-content-center flex-column">
    <div class="row justify-content-between bnr-form-w3ls">
      <div class="col-lg-3">
        <h4><%= t "slogan" %></h4>
      </div>
      <div class="col-lg-9">
        <%= form_with url: jobs_path, method: :get, id: "search-form", local: true do %>
          <div class="row">
            <div class="col-md-3 form-group mb-md-0">
              <label class="text-capitalize">
                <%= t "find_by_career" %>
              </label>
              <%= text_field_tag :career_name, params[:career_name],
                class: "form-control", placeholder: t("search_career") %>
            </div>
            <div class="col-md-5 form-group mb-md-0">
              <label class="text-capitalize">
                <%= t "find_by_company" %>
              </label>
              <%= text_field_tag :company_name, params[:company_name],
                class: "form-control", placeholder: t("search_company") %>
            </div>
            <div class="col-md-3 form-group mb-md-0">
              <label class="text-capitalize">
                <%= t "find_by_job" %>
              </label>
              <%= text_field_tag :job_info, params[:job_info],
                class: "form-control", placeholder: t("search_job") %>
            </div>
            <div class="col-md-1 form-group search">
             <button type="submit" class="btn btn-w3ltd btn-block w-100 bg-theme font-weight-bold"><span
                class="fa fa-search"></span>
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> flash"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= wicked_pdf_stylesheet_link_tag "pdfs" %>
    <%= wicked_pdf_javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <%= yield %>
  </body>
</html>